# Generated by Django 3.1.14 on 2026-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260115_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_cho',
            field=models.BooleanField(default=False),
        ),
    ]
