# Generated by Django 3.1.14 on 2026-01-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topic_is_cho'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='source_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.note'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.TextField(),
        ),
    ]
