# Generated by Django 3.1.14 on 2026-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260115_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_datesheet_entry',
            field=models.BooleanField(default=False),
        ),
    ]
