# Generated by Django 3.1.14 on 2026-01-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260116_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
